#for development in Docker
version: "3"
services:
  node:
    build: .
    container_name: plant_node
    environment:
      - NODE_ENV=development
      - TZ=Europe/Zurich
    restart: always
    ports:
      - 80:3000 #app
      - 8080:8080 #socketServer
    command: npm run dev #while development run webpack --watch in a second terminal for sass->css live conversion, or use other compiler
    links: 
      - mongo
    volumes:
      - ./:/home/app #mount current folder into container for development
  mongo:
    container_name: plant_mongo
    restart: always
    command: [--auth]
    environment:
      TZ: Europe/Zurich
      MONGO_INITDB_ROOT_USERNAME: ${DB_ADMIN} #set in .env (has to be in same directory as composefile)
      MONGO_INITDB_ROOT_PASSWORD: ${DB_ADMIN_PW} #these variables have no impact on dbs already created. for example in a mounted volume at build time
    image: mongo:3.6-xenial
    ports:
      - 27017:27017
    volumes:
      - DATA:/data/db
     # - ./data/db:home/app/data/db
volumes:
  DATA: